import fs from 'node:fs';
import path from 'node:path';

const START = '<!-- GLOBAL-AI-RULES:START -->';
const END = '<!-- GLOBAL-AI-RULES:END -->';
const NOTE =
  '<!-- Generated by @pixpilot/agent-config-sync. Edit GLOBAL-AI-RULES.md in the configuration directory. -->';
const COPILOT_FRONTMATTER = [
  '---',
  'description: Always-on personal response-style and behaviour rules.',
  "applyTo: '**'",
  '---',
  '',
].join('\n');

/** Extracts reusable rules from either a source file or an existing managed target. */
export function extractRules(contents: string): string {
  const start = contents.indexOf(START);
  const end = contents.lastIndexOf(END);
  const managed = start !== -1 && end > start ? contents.slice(start + START.length, end) : contents;

  return managed
    .replace(/^\s*<!--[^>]*-->\s*/u, '')
    .replace(/^\s*<!--[^>]*-->\s*/u, '')
    .trim();
}

/** Applies one managed global-rules block without overwriting user-owned text. */
export function applyRules(existing: string, rules: string): string {
  const block = `${START}\n${NOTE}\n\n${rules.trim()}\n\n${END}`;
  const start = existing.indexOf(START);
  const end = existing.lastIndexOf(END);

  if (start !== -1 && end > start) {
    return `${existing.slice(0, start)}${block}${existing.slice(end + END.length)}`;
  }

  const base = existing.trim();
  return base === '' ? `${block}\n` : `${base}\n\n${block}\n`;
}

/** Writes rules in the target format, preserving Claude and Codex user content. */
export function syncRules(source: string, target: string, isCopilot: boolean): string {
  const rules = extractRules(fs.readFileSync(source, 'utf8'));
  fs.mkdirSync(path.dirname(target), { recursive: true });
  const contents = isCopilot
    ? `${COPILOT_FRONTMATTER}${applyRules('', rules)}`
    : applyRules(readIfExists(target), rules);
  fs.writeFileSync(target, contents.endsWith('\n') ? contents : `${contents}\n`);
  return target;
}

function readIfExists(filePath: string): string {
  return fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : '';
}
